### ISSUE TITLE
React Select

### ISSUE THREAD

**Issue by jossmac** [gianmarcotoso/react-ui-autocomplete#1]
Hi @gianmarcotoso!

This looks really cool. Just thought I'd mention [React Select](http://jedwatson.github.io/react-select) - it's had a great deal of time spent on it, and may meet your needs :)

**Comment by gianmarcotoso** [comment]
Thank you for your suggestion. As this is not an issue with my component but an attempt to promote yours, I'm sorry but I'll close the issue and delete your comment. Do feel free to contribute to the component itself though, as I see you already have much experience on the matter!
